esphome:
  name: esp32

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "ss"

# Enable Web Server
web_server:
  port: 80  # Default HTTP port

# Enable OTA updates
ota:
- platform: esphome
  password: "nopswforu"

# Define a switch on GPIO 2
switch:
  - platform: gpio
    pin: 2
    name: "LED Control"
    id: led_switch 

output:
  - platform: ledc
    pin: 13
    id: pwm_output

light:
  - platform: monochromatic
    output: pwm_output
    name: "Custom LED Brightness"

# Wi-Fi Configuration
wifi:
  ssid: "beep0"
  password: "48safandra"

  manual_ip:
    static_ip: 192.168.18.84  # Change this to fit your network
    gateway: 192.168.1.1       # Your router’s IP
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case Wi-Fi fails
  ap:
    ssid: "ESP32 Failsafe AP"
    password: "sergiuloh65"

# Enable Captive Portal
captive_portal:
